### PR TITLE
Add background bubble to chat messages

### PR DESCRIPTION
**Pull request by Jei**
Solves #69 
Screenshot_1585731328

I replaced ListTile with a Column widget, since the `ListTile.title` text is not supposed to wrap, and the `ListTile.subtitle` should be 2 lines at most. This should also make things easier when we decide to add more data to the message (username, timestamp...).

### CODE REVIEW

**Comment by nickmeinhold** [comment]
Looks great man! I can't test at the moment because the build fails (pretty certain it's a signing problem that I've caused by nuking all certs when I was working on a different project). 

Happy to do the Approve without testing if you would like (?) - but could we try and push through #60 before other PRs?  It's been hanging around and touches a lot of files so would be a good one to not leave too long.

**Comment by nickmeinhold** [comment]
I figured out the build issue - unrelated to this PR and I've put up a PR with a fix (#73) 

Tested on iOS and looks great!

**Review by nickmeinhold — APPROVED** [review]

**Comment by Jei** [comment]
> Happy to do the Approve without testing if you would like (?) - but could we try and push through #60 before other PRs? It's been hanging around and touches a lot of files so would be a good one to not leave too long.

You're right. I'll wait until #60 is merged so I can fix any linting issues before merging this.

**Comment by Jei** [comment]
Still looks good after getting the changes from #60. Merging!

**Pull request merged**
