### PR TITLE
Flutter Platform Widgets

### PR DESCRIPTION
**Pull request by Jei**
I've tried to play with the [flutter_platform_widgets](https://pub.dev/packages/flutter_platform_widgets) package a bit. Here are my impressions:

**Pros:**
- The library covers most of the UI components shared by Android and iOS (app bar, bottom bar, dialogs...);
- All the widgets accept separate custom options for Android and iOS;
- When working with standard UI components, it reduces the boilerplate required to handle different platforms/designs.

**Cons:**
- Using the PlatformApp and PlatformProvider widgets prevent the platform selector in the Android Studio's inspector from working. PlatformProvider still allows to select a different platform manually;
- Using material widgets (like ListTile) while running on iOS requires the use of an `iosUsesMaterialWidgets` option in PlatformProvider, or to wrap each component inside a Material widget (see https://github.com/aqwert/flutter_platform_widgets/issues/122). I've opted for the former solution.

Overall, I think that this library could save us some time in the future, but it's a pretty serious change to our current codebase, and it has some quirks that require occasional searching in the README/issues. I wanted to know your opinion before going forward with it.

### CODE REVIEW

**Comment by nickmeinhold** [comment]
Hey mate!  Thanks for excellent write-up of your findings.  I don't have experience with the package but your write-up of the pros and cons aligns with the (limited) understanding I've gleaned from forums and such.  

Initially when we spoke about this my opinion was that, while I prefer to heavily customise the look and feel of Material widgets to something that isn't really Androidy or iOSy, I hadn't done an app with Cupertino on iOS (via flutter_platform_widgets) and was keen to learn at some stage so I was abstaining from a vote.  On reflection I actually feel the chat app is better suited to the former (customised Material widgets) because I think it would be more interesting and fun to play with a unique design without being too concerned about the design constraints of either platform.  In this context (of a chat app) I personally don't see a reason to go down that route as the design constraints particular to a chat app are very well known to most people and I can't think of any features and corresponding UI we might do that would be better off as Androidy and iOSy (if I'm making any sense)?  I think there's a bit of an unknown here too in that we don't know how difficult it might end up being as we go further along and want to customise designs or add features.  I realised at some point that my preference would be to dig in to the Cupertino/flutter_platform_widgets thing when there is an app that has a strong reason for doing so, initially I was thinking of the ptv_clone app that I recently added to the adventuresin github account as I assumed it was native and would look quite different on each platform but when I went to check it looks much the same so I assume they used a cross-platform tool to build it.  

What I'm trying to say is I would (if no-one minds) like to switch my vote to using Material on both platforms.  Sorry if that's annoying given you've already done the work.  I'm cool if it's decided I can't switch my vote and it goes back to not counting :-)

**Comment by nickmeinhold** [comment]
I read through the code, looks great, good job @Jei!  

Do you want a code review?  If so, I'll have a more thorough read, test on my phone then approve but if we decide to go this way, code all looks good to me!

**Comment by Jei** [comment]
> On reflection I actually feel the chat app is better suited to the former (customised Material widgets) because I think it would be more interesting and fun to play with a unique design without being too concerned about the design constraints of either platform.

I see your point. Using libraries like flutter_platform_widgets could subtract something from learning how to build a UI in Flutter.

> I think there's a bit of an unknown here too in that we don't know how difficult it might end up being as we go further along and want to customise designs or add features.

That's true. While it would still be possible to create custom widgets, I know by experience that this kind of library tends to introduce unexpected side effects.
 
> What I'm trying to say is I would (if no-one minds) like to switch my vote to using Material on both platforms. Sorry if that's annoying given you've already done the work. I'm cool if it's decided I can't switch my vote and it goes back to not counting :-)

It's really not a problem. I learnt something new, and I could still try to use the library in another project. Also, I knew from the start that the use of Material/Cupertino/custom design in the chat app was still an open topic.
And honestly, I prefer Material design anyway 😬

> Do you want a code review? If so, I'll have a more thorough read, test on my phone then approve but if we decide to go this way, code all looks good to me!

Could you test it on an iPhone? I just wanted to know if there are any bugs on iOS, and I don't trust the platform selection tool in Android Studio to actually show them.

**Comment by nickmeinhold** [comment]
OK awesome, cheers mate!

Tested just now, it ran fine but had a couple of issues in UI, all AppBar related I think: 

IMG_4487

IMG_4489

IMG_4488

**Comment by Jei** [comment]
Thank you!
I solved the problem with the avatar in the app bar with a similar solution to this: https://github.com/flutter/flutter/issues/29880
Showing the back chevron on iOS was just a matter of adding the `cupertino_icons` package to the project.

I'll close the PR, since we want to continue using a custom/Material design mix.

**Pull request closed without merging**
