### PR TITLE
Setup emulator suite for prototyping & testing

### LINKED ISSUE #153: Setup firebase emulator suite for prototyping & testing
[Introduction to Firebase Local Emulator Suite](https://firebase.google.com/docs/emulator-suite)

- [x] instructions in README 
- [x] default data in test/data 
- [x] new entry point that connects to emulated Firestore

### PR DESCRIPTION
**Pull request by nickmeinhold**
Fixes #153

- set the firestore emulator to use port 8081
- added notes to the README on how to setup and use
- added launch option for entry point that uses local firestore emulator
- incidentally updated functions dependencies and cocoapods versions
- renamed MyApp to ChatApp and moved to separate file
- added entry point that connects Firestore instance to local emulators
- setup firestore emulator with basic data, exported for use as default

### CODE REVIEW

**Comment by gaslitbytech** [comment]
Sorry this is just a quick rough note. That I didn't have many of the tools to use the emulators as I haven't built or deployed hte firebase functions previously. It not obvious to be how to build the typescript. What I tried

```sh
npm run build
npm run build functions/src/
npm run build functions
```

```text
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/david/Focus/meetup-chatapp/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/david/Focus/meetup-chatapp/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/david/.npm/_logs/2020-06-06T23_13_07_491Z-debug.log

```

What I had to install this morning.

```sh
firebase emulators:start --import=test/data
curl -sL https://firebase.tools | bash
firebase emulators:start --import=test/data
npm install firebase-admin --save
firebase emulators:start --import=test/data
npm install firebase-functions
firebase emulators:start --import=test/data
```

And what I added the following morning to get this working

```sh
  cd functions/
  npm run build
  npm install typescript -g
  npm run build
  firebase login
  npm --version
  cd ..
  firebase emulators:start --import=test/data
```

**Comment by nickmeinhold** [comment]
Thanks @tourdownunder ! 

I thought about putting some more info in the README about potentially needing to build the functions but I decided the error messages were clear enough that it would be better to rely on them... clearly this was not a fair assumption, sorry about that!  I guess it's easy to mistakenly think something is clear when you already know what it's telling you :-) 

Did you get it running in the end?  From memory, if I went to a branch that didn't have the cloud functions built, and tried running `firebase emulators:start --import=test/data` the error message prompted me to run `npm run build` from the `functions` directory.  Was that not the case for you? 

If you do run `npm run build` from the `functions` directory, does that allow you to then run `firebase emulators:start --import=test/data`?  

EDIT: I imagine `firebase emulators:start --import=test/data` has to be run from the project directory. 

Thanks for working on this!

**Comment by gaslitbytech** [comment]
Thanks @nickmeinhold. 

Your comment put me on the right track and I've appended a snippet of my history to the previous comment. 

Well done having a local copy of firebase functions in a dev environment is brilliant.

**Review by gaslitbytech — APPROVED** [review]
Great Work. I tested it all worked on my dev environment. For people that don't work with front end tools such as npm some guidelines on the wiki would be good. I will otherwise likely need to use our comments in this PR as a reference for when I reinstall.

**Comment by nickmeinhold** [comment]
Thanks @tourdownunder ! 

I used your description and had a go at a wiki page like you suggested: [Development Environment · Adventures-In/chat_app Wiki](https://github.com/Adventures-In/chat_app/wiki/Development-Environment)... please feel free to edit!

**Pull request merged**
