### PR TITLE
i173: Get macOS version running

### LINKED ISSUE #173: Get macOS version running

### PR DESCRIPTION
**Pull request by nickmeinhold**
Fixes #173 

Notes for running:
- you'll need to add `GoogleServices-Info.plist` -> copy from `ios/Runner/` to `macos/Runner/` 
- `sign_in_with_apple` on *macOS* wants the system user password, not the password of the Apple Id you use for iCloud etc.

### CODE REVIEW

**Comment by gaslitbytech** [comment]
I found that I needed to:

```sh
flutter config --enable-macos-desktop
```

found in these steps in [docs](https://flutter.dev/desktop)

Though once 

```sh
flutter run -d macos
```

I got this issue

```text
Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update
```

Unfortunately It didn't work and wasn't very descriptive

```text
$ flutter run -d macOS
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                            109.8s
** BUILD FAILED **                                                      
                                                                        
Building macOS application...                                           
Exception: Build process failed
```

Hangon. 

Just tried to reboot VS Code and when that didn't fix it Booted Xcode with the greetings of:

Screen Shot 2020-06-29 at 9 30 51 pm

Still failed though a bit more descriptive error:

``` text
 flutter run -d macOS
Launching lib/main.dart on macOS in debug mode...
2020-06-29 21:33:14.399 XCBBuildService[42834:699101] Failed to remove: /Users/david/Projects/meetup-chatapp/build/macos/Build/Intermediates.noindex/XCBuildData/4c49be1e4618fba7b883c82ccd5d7676-desc.xcbuild: unlink(/Users/david/Projects/meetup-chatapp/build/macos/Build/Intermediates.noindex/XCBuildData/4c49be1e4618fba7b883c82ccd5d7676-desc.xcbuild): No such file or directory (2)
** BUILD FAILED **                                                      
                                                                        
Building macOS application...                                           
Exception: Build process failed
```

**Comment by nickmeinhold** [comment]
> I found that I needed to:
>   flutter config --enable-macos-desktop

Sorry about that! I've added a note to the README about needing to enable macos. 

> a bit more descriptive error

Looks like it needs a clean - the file it's looking for is an intermediate in the `build` folder so I'd say start from `flutter clean` and hopefully you won't need to go any more nuclear than that :-)

**Comment by gaslitbytech** [comment]
Seem to have got the following error when using at Xcode to build

Screen Shot 2020-06-30 at 5 40 39 am

After clicking `Register` Xcode seems to have build okay. 

And now building in VS Code using `flutter run -d macos` is good.

**Review by gaslitbytech — APPROVED** [review]
Thanks for the note about clean @nickmeinhold. It helped along with building with Xcode once to Install additional components and to register the laptop as a device.

**Comment by nickmeinhold** [comment]
Thanks for your efforts @tourdownunder , great job sorting it out!  I'll add an issue about needing to register the device.

**Pull request merged**
