### PR TITLE
Create new Facebook app and change config settings

### LINKED ISSUE #28: Create a new Facebook app and update project config for Facebook sign in
I did originally create a new Facebook app specifically for the chat app but somewhere along the line I realised the config details (app id, etc.) we were using was from an old Facebook app of mine called Good Food and the Facebook app I created had disappeared.  Bit of a weird mystery.  

Anyway we just need to: 
- [x] create a new Facebook app, called something like "Adventures In Chat App" 
- [x] update the config setting in the Firebase console 
- [x] update the Facebook app config settings (eg. whitelisted Urls, etc.)

### PR DESCRIPTION
**Pull request by nickmeinhold**
fixes #28

### CODE REVIEW

**Comment by Jei** [comment]
Could you add me as a developer of the Facebook App? I wanted to test the Facebook login on Android.

**Comment by nickmeinhold** [comment]
@Jei yeah sorry man - I asked you on discourse: need your fbid or... maybe username...?  I posted a screen shot of what we need on discourse

**Comment by nickmeinhold** [comment]
@Jei or add me on facebook https://www.facebook.com/nick.meinhold

**Comment by Jei** [comment]
Whoops, I didn't see the message (it still went into the spam folder, I'm creating a filter right now). I'll add you on FB.

**Comment by nickmeinhold** [comment]
Sweet!  Added you to the facebook app

**Comment by Jei** [comment]
Ok, it's working as intended. Logging in with Facebook still gives me the `ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL" message, but it will be solved by #30

**Comment by nickmeinhold** [comment]
@Jei I had the same error - I think it's because the device is still 'signed in' with the old facebook app.  As we haven't added the Facebook sign out to our sign out feature yet I just deleted the app and reinstalled.

**Pull request merged**
