### PR TITLE
Update Android NDK version (21.1.6352462)

### LINKED ISSUE #96: Fix cause of failing ios build in CI
I added an android build to the ios workflow at some point as I was going to ask if people were interested in having just a single workflow that runs on macOS and builds, tests and deploys both iOS and Android. Now we are getting the error: 

```
 No version of NDK matched the requested version 21.0.6113669. Versions available locally: 18.1.5063045, 21.1.6352462, 21.1.6352462
```

see [Add notifications (#85) · adventuresin/chat_app@cbf472b](https://github.com/adventuresin/chat_app/runs/638389118?check_suite_focus=true)

The latest NDK on macOS is older than the one on the linux workflow, hence the error. 

I am still interested in having that conversation as I think there is a lot of benefit to a single workflow but I will just remove the Android build in the iOS workflow for now to get us back to green.

### PR DESCRIPTION
**Pull request by Jei**
Update the Android NDK to 21.1.6352462 to comply with the version available on the macOS virtual environment.

fixes #96

### CODE REVIEW

**Comment by Jei** [comment]
@nickmeinhold I've also cherry picked 982cffe31c9db531caaa1cdae27eaa63bb6626ea to run the workflows on the dev branch.

**Comment by nickmeinhold** [comment]
Awesome work! If we make a decision on #102 we could potentially drop the android workflow in this PR rather than making changes that might not be needed anyway... what do you think?

**Comment by Jei** [comment]
@nickmeinhold I don't think I have access to the repository settings, could you remove the check for the Android workflow?

**Comment by nickmeinhold** [comment]
Oh cool... I'm on it!

Btw, we should probably rename the workflow - I tried a series of names on another project that were never right, because I was using the same workflow but checking the branch and push/pr status to do some combination of build & test or build, test and deploy.  I think something vague might be best...

**Comment by nickmeinhold** [comment]
OK done! I think I'll have to do the same thing again if we rename, just FYI @Jei

**Review by nickmeinhold — APPROVED** [review]
Nice one mate!

**Pull request merged**
